### ISSUE TITLE
Does all this resolve at compile time?

### ISSUE THREAD

**Issue by JeffreySarnoff** [ninjaaron/CcallMacros.jl#3]
The syntax is an improvement, thanks for the effort.  It is not immediately clear to me if some of the activity, for example the implicit introduction of `convert(Ctype, x)`, would incur runtime overhead that `ccall` does not.

**Comment by ninjaaron** [comment]
`convert` may or may not incur a runtime cost, depending on the type which is being converted.

In any case, ccall does exactly the same thing internally:

```julia
julia> f() = ccall(:strlen, Csize_t, (Cstring,), "foo")
f (generic function with 1 method)

julia> @code_lowered f()
CodeInfo(
1 ─ %1 = Base.cconvert(Main.Cstring, "foo")
│   %2 = Base.unsafe_convert(Main.Cstring, %1)
│   %3 = $(Expr(:foreigncall, :(:strlen), UInt64, svec(Cstring), 0, :(:ccall), :(%2), :(%1)))
└──      return %3
)
```

So, it may have a runtime cost, but it has no _additional_ runtime cost vis à vis `ccall`.

There is one case where there is an an additional check which may or may not happen at runtime beyond what `ccall` does: It checks that function pointers are of the type `Ptr{Cvoid}`. If your code is type stable, this check will compile out, but if it is not, it will occur at runtime. That is to say, you only pay for it if your code is broken to start with and you get an error telling you to fix it.

Also note that the `@ccall` macro is now available in Julia 1.5 in Base, so this package is no longer necessary if you upgrade to the latest version of Julia.
